# Generated by Django 4.2.6 on 2023-10-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(
                null=True, upload_to="profile_pics", verbose_name="Profile Picture"
            ),
        ),
    ]
