# Generated by Django 4.2.5 on 2023-11-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_user_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_pics",
                verbose_name="Profile Picture",
            ),
        ),
    ]
