# Generated by Django 4.2.6 on 2023-10-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tube", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="id",
        ),
        migrations.AlterField(
            model_name="video",
            name="videoID",
            field=models.CharField(
                max_length=20,
                primary_key=True,
                serialize=False,
                verbose_name="Youtube Video Id",
            ),
        ),
    ]
