# Generated by Django 4.2.5 on 2023-11-01 14:46

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tube", "0003_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="comment_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
