# Generated by Django 4.2.5 on 2023-11-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tube", "0007_alter_video_uploader"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="Category",
            field=models.CharField(
                choices=[
                    ("MUSIC", "Music"),
                    ("ANIFILM", "Animation and Film"),
                    ("PETS", "Pets and Animals"),
                    ("SPORTS", "Sports"),
                    ("GAMING", "Gaming"),
                    ("NEWS", "News"),
                    ("POLITICS", "Politics"),
                    ("EDUCATION", "Education"),
                    ("SCITECH", "Science And Technology"),
                    ("OTHERS", "Others"),
                ],
                default="OTHERS",
                max_length=30,
            ),
        ),
    ]
