# Generated by Django 4.2.5 on 2023-11-04 18:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tube", "0008_video_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="Category",
            new_name="category",
        ),
    ]
